version: '3.8'
services:
  web:
    image: 'web:robo'
    container_name: web
    depends_on:
      - catalogue
  mongo:
    image: 'mongodb:robo'
    container_name: mongodb
  catalogue:
    image: 'catalogue:robo'
    container_name: catalogue
    depends_on:
      - mongodb
  user:
    image: 'user:robo'
    container_name: user
    depends_on: mongodb redis
networks:
  roboshop-network:
    driver: bridge
redis:
  image: redis
