version: '3.8'
services:
  web:
    image: 'web:robo'
    container_name: web
    depends_on:
      - catalogue
  mongodb:
    image: 'mongodb:robo'
    container_name: mongodb
  catalogue:
    image: 'catalogue:robo'
    container_name: catalogue
    depends_on:
      - mongodb
  redis:
    image: redis
  user:
    image: 'user:robo'
    container_name: user
    depends_on: 
      - mongodb 
      - redis
  ports:
    -"80":"80"
networks:
  roboshop-network:
    driver: bridge