version: '3.8'
services:
  web:
    image: 'web:robo'
    container_name: web
    ports:
      - '80:80'
  mongodb:
    image: 'mongo:robo'
    container_name: mongodb
  catalogue:
    image: 'catalogue:robo'
    container_name: catalogue
    depends_on:
      - mongodb
  redis:
    image: redis
  user:
    image: 'user:robo'
    container_name: user
    depends_on:
      - mongodb
      - redis
  cart:
    image: 'cart:robo'
    container_name: cart
    depends_on:
      - redis
  shipping:
    image: 'shipping:robo'
    container_name: shipping
    depends_on:
      - mysql
  mysql:
    image: 'mysql:robo'
    container_name: mysql
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
  payment:
    image: "payment:robo"
    container_name: payment
    depends_on:
      - rabbitmq
networks:
  roboshop-network:
    driver: bridge
